# Generated by Django 3.1.2 on 2020-10-26 20:14

from django.db import migrations, models
import django.db.models.deletion
import jet_lend.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('patponymic', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ST1', 'Первый этап завершен'), ('ST2', 'Второй этап завершен'), ('ST31', 'Третий этап завершен загрузкой документа'), ('ST32', 'Третий этап завершен отказом от квалификации')], default='ST1', max_length=4)),
                ('accept_rules', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='jet_lend.investor')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveSmallIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=3000)),
                ('date_of_issue', models.DateField()),
                ('issued_by', models.CharField(max_length=3000)),
                ('code_subdivision', models.PositiveIntegerField()),
                ('registration_address', models.CharField(max_length=3000)),
                ('screen_part1', models.FileField(upload_to=jet_lend.utils.upload_to)),
                ('screen_part2', models.FileField(upload_to=jet_lend.utils.upload_to)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='jet_lend.investor')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=500)),
                ('doc_screen', models.FileField(upload_to=jet_lend.utils.upload_to)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jet_lend.investor')),
            ],
            options={
                'verbose_name': 'Квалификационный документ',
                'verbose_name_plural': 'Квалификационные документы',
            },
        ),
    ]
